spellings_website/app/baldpanda_site/worksheets/forms.py
"""Forms for adding sentences to db and
submitting required words to worksheet
"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class NewSentence(FlaskForm):
    """Form for adding new sentence to db"""
    sentence = StringField('Please enter a sentence you would like to add.', validators=[DataRequired()])
    submit = SubmitField('Submit')

class WordsForSheet(FlaskForm):
    """Form for submitting required words for worksheet"""
    words = StringField("Please enter the spellings for the worksheet,\
     separating them using a comma.", validators=[DataRequired()])
    submit = SubmitField('Make Worksheet')

class SentenceToDelete(FlaskForm):
    """Form for finding sentence user would like to delete"""
    sentence = StringField('Please enter part of sentence you would like to delete.'\
    , validators=[DataRequired()])
    submit = SubmitField('Find Sentence To Delete')

class DeleteSentence(FlaskForm):
    """Form for deleting a sentence"""
    sentence = StringField('Would you like to delete the following sentence?'\
    , validators=[DataRequired()])
    submit = SubmitField('Delete Sentence')

spellings_website/app/baldpanda_site/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html')

spellings_website/app/baldpanda_site/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from baldpanda_site.users.utils import send_reset_email
from baldpanda_site import db, bcrypt
from baldpanda_site.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from baldpanda_site.models import User

users = Blueprint('users', __name__)

@users.route('/registration', methods = ['GET', 'POST'])
def registration_page():
    form = RegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        flash(f'Account created successfully for {form.username.data}.', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', form = form)

@users.route('/login', methods = ['GET', 'POST'])
def login_page():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful', 'danger')
    return render_template('login.html', form = form)

@users.route('/logout')
def logout_page():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login_page'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return(redirect(url_for('users.reset_password')))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated', 'success')
        return redirect(url_for('users.login_page'))
    return render_template('reset_token.html', title='Reset Password', form=form)

spellings_website/app/baldpanda_site/worksheets/routes.py
"""Routes associated with spelling worksheets"""
from flask import render_template, url_for, redirect, Blueprint, flash
from flask_login import login_required, current_user
from baldpanda_site import db
from baldpanda_site.worksheets.sentences.example_sentence import ExampleSentence
from baldpanda_site.worksheets.forms import  WordsForSheet, NewSentence, SentenceToDelete, DeleteSentence
from baldpanda_site.models import Sentence
from baldpanda_site.worksheets.blanked_words.six_words_with_spaces import SixWordsWithBlanks

worksheets = Blueprint('worksheets', __name__)

@worksheets.route('/worksheet', methods=['GET', 'POST'])
def spelling_page():
    """Form for passing words to word_search method"""
    form = WordsForSheet()
    sentence_list = []
    if form.validate_on_submit():
        words_for_search = form.words.data
        words_for_search = words_for_search.replace(" ", "")
        words_for_search = words_for_search.replace(",", "+")
        return redirect(url_for('worksheets.word_search', words=words_for_search))
    return render_template('wordsearch.html', sample_sentences=sentence_list, form=form)

@worksheets.route('/worksheet/<string:words>')
def word_search(words):
    sentence_list = [[],[]]
    words_list = words.split('+')
    words_for_page = words.replace('+', ', ')
    words_not_in_db = ''
    for word in words_list:
        six_words = SixWordsWithBlanks()
        sentence_list[0].append(six_words.generate_six_words_with_blanks(word))
        string_to_query_in_middle = f"% {word} %"
        sentence = Sentence.query.filter(Sentence.sentence.like(string_to_query_in_middle)).first()
        if sentence:
            sentence_with_blanks = ExampleSentence(sentence.sentence)
            sentence_with_blanks.sentence = sentence_with_blanks.remove_space_before_and_after_punct(
            [",",".", "!", "?",'"'])
            sentence_list[1].append(sentence_with_blanks.blank_out_word_in_sentence(word))
        else:
            words_not_in_db += word + "+"
    if len(words_not_in_db) == 0:
        return render_template('worksheet.html', sample_sentences=sentence_list, words=words_for_page)
    else:
        words_not_in_db = words_not_in_db[:-1]
        return redirect(url_for('worksheets.sentence_adder', words_to_add=words_not_in_db))

@worksheets.route('/sentence/<string:words_to_add>', methods=['GET', 'POST'])
@login_required
def sentence_adder(words_to_add):
    """Add new sentence to db"""
    form = NewSentence()
    if form.validate_on_submit():
        sentence_to_add_to_db = ExampleSentence(form.sentence.data)
        sentence = " " + sentence_to_add_to_db.add_space_before_and_after_punct(\
        [",", ".", "!", "?", '"'])
        sentence = Sentence(sentence=sentence, user_id=current_user.id)
        db.session.add(sentence)
        db.session.commit()
        flash('Your sentence has been added', 'success')
        return redirect(url_for('worksheets.spelling_page'))
    return render_template('sentence_adder_page.html', title='sentence_adder',\
    form=form, words_to_add=words_to_add)

@worksheets.route('/sentence/delete_page/<string:sent>', methods=['GET', 'POST'])
def find_sentence_to_delete(sent):
    """Find sentence in db to delete given word"""
    string_to_query_in_middle = f"% {sent} %"
    sentence = Sentence.query.filter(Sentence.sentence.like(string_to_query_in_middle)).first()
    if sentence:
        sentence_with_blanks = ExampleSentence(sentence.sentence)
        sentence.sentence = sentence_with_blanks.remove_space_before_and_after_punct(\
        [",", ".", "!", "?", '"'])
        return render_template('delete_sentence_page.html', sample_sentence=sentence)
    else:
        return render_template("home.html")

@login_required
@worksheets.route('/sentence/delete/<int:sentence_id>', methods=['POST'])
def delete_sentence(sentence_id):
    """Delete sentence from db"""
    sentence = Sentence.query.get_or_404(sentence_id)
    db.session.delete(sentence)
    db.session.commit()
    flash('The sentence has been deleted!', 'success')
    return render_template("home.html")

@worksheets.route('/sentence/delete_page/', methods=['GET', 'POST'])
def delete_sentence_page():
    """Page for searching for sentence to delete"""
    form = SentenceToDelete()
    if form.validate_on_submit():
        sentence_for_search = form.sentence.data
        return redirect(url_for('worksheets.find_sentence_to_delete', sent=sentence_for_search))
    return render_template('sentence_to_delete_search.html', form=form)

spellings_website/app/baldpanda_site/templates/delete_sentence_page.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Remove Sentence</legend>
      <div class="form-group">
          Would you like to delete the following sentence?
      </div>
      <div class="form-group">
        <b>{{sample_sentence.sentence}}</b>
      </div>
      <div class="form-group">
        <form action="{{ url_for('worksheets.delete_sentence', sentence_id=sample_sentence.id)}}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
      </div>
    </fieldset>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <body>
    <p><div style="width:100%;height:0;padding-bottom:75%;position:relative;"><iframe src="https://giphy.com/embed/uSYQsJQWEv6O4" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div></p>
  </body>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% if title %}
    <title> {{title}}</title>
    {% else %}
    <title> Spelling Worksheet</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href={{ url_for('main.home') }}>BaldPanda</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href={{ url_for('worksheets.spelling_page') }}>Worksheets</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <div class="dropdown">
                <button class="dropbtn">
                    &#9776;
                  </button>
                  <div class="dropdown-content">
                    <a class="nav-item nav-link" href={{ url_for('worksheets.sentence_adder', words_to_add='default') }}>Add Sentence</a>
                    <a class="nav-item nav-link" href={{ url_for('worksheets.delete_sentence_page', words_to_add='default') }}>Remove Sentence</a>
                    <a class="nav-item nav-link" href={{ url_for('users.logout_page') }}>Logout</a>
                  </div>
              </div>
              {% else %}
                <a class="nav-item nav-link" href={{ url_for('users.login_page') }}>Login</a>
                <a class="nav-item nav-link" href={{ url_for('users.registration_page') }}>Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

spellings_website/app/baldpanda_site/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Login</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class = "form-check-input") }}
        {{ form.remember.label(class = "form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_password')}}">Forgot Password</a>
      </small>
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Need an account: <a href="{{url_for('users.registration_page')}}">Sign Up</a>
  </small>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Register</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }}
        {% if form.username.errors %}
          {{ form.username(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.username(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label") }}
        {% if form.confirm_password.errors %}
          {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.confirm_password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Already Have an Account: <a href="{{url_for('users.login_page')}}">Sign In</a>
  </small>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for password in form.email.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label") }}
        {% if form.confirm_password.errors %}
          {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.confirm_password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/sentence_adder.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Add Sentence</legend>
      <div class="form-group">
        {{ form.sentence.label(class="form-control-label") }}
        {% if form.sentence.errors %}
          {{ form.sentence(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.sentence.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.sentence(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/sentence_adder_page.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Add Sentence</legend>
      {% set list_of_words = words_to_add.split('+') %}
      <div class="form-group">
        {% if words_to_add!="default" %}
        <div class="adding-custom-words-form">
          Please enter a sentence with the word <b>{{words_to_add|replace("+", " or ")}}</b> in.
          </div>
        {% else %}
          {{ form.sentence.label(class="form-control-label") }}
        {% endif %}
        {% if form.sentence.errors %}
          {{ form.sentence(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.sentence.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
            {{ form.sentence(class="form-control form-control-lg") }}
          {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-danger m-1") }}
    </div>
  </form>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/sentence_to_delete_search.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delete Sentence</legend>
      <div class="form-group">
        {{ form.sentence.label(class="form-control-label") }}
        {% if form.sentence.errors %}
          {{ form.sentence(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.sentence.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.sentence(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/spellings.html
{% extends "layout.html" %}
{% block content %}
  {% for sentence in sample_sentences %}
    <body>
      <p>{{sentence}}</p>
    </body>
  {% endfor %}
{% endblock content%}

spellings_website/app/baldpanda_site/templates/wordsearch.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method=POST action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Make Worksheet</legend>
      <div class="form-group">
        {{ form.words.label(class="form-control-label") }}
        {% if form.words.errors %}
          {{ form.words(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.words.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.words(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content%}

spellings_website/app/baldpanda_site/templates/worksheet.html
{% extends "layout.html" %}
{% block content %}
{% if words %}
<div class="adding-spacing-worksheet-sections">
  <body>
  The words for this sheet's spellings are: <b> {{ words }} </b>
  </body>
{% endif %}
</div>
<div class="adding-spacing-worksheet-sections">
  <p>
    {% set words_with_spaces = sample_sentences[0]%}
      {% for line in words_with_spaces %}
      <body>
        <p>{{line}}</p>
      </body>
      {% endfor %}
  </p>
</div>
<div>
  <p>
    {% set sentences_with_blanks = sample_sentences[1]%}
      {% for sentence in sentences_with_blanks %}
      <body>
        <p>{{sentence}}</p>
      </body>
      {% endfor %}
  </p>
</div>
{% endblock content%}